arrowParens: always
bracketSpacing: true
endOfLine: lf
jsxBracketSameLine: true
jsxSingleQuote: false
printWidth: 120
proseWrap: preserve
quoteProps: preserve
semi: true
singleQuote: true
tabWidth: 4
trailingComma: es5
